### ISSUE TITLE
how to set the "weight_eyes"?

### ISSUE THREAD

**Issue by ruanjiyang** [sberbank-ai/sber-swap#17]
Dear sberbank-ai, I try to train on my datasets. and want to know how to set the weight_eyes?  should I put 10 for weitght_eyes?

thanks!

**Comment by AlexanderGroshev** [comment]
@ruanjiyang you should use eye_detector_loss=True and set some value on weight_eyes. We recommend to set weitght_eyes around 800.

**Comment by ruanjiyang** [comment]
Dear AlexanderGroshev.

Thanks very much for your feedback. I will follow your suggestion.

The followings are the parameters which used for my training. 

parser.add_argument('--weight_adv', default=1, type=float, help='Adversarial Loss weight')
   parser.add_argument('--weight_attr', default=10, type=float, help='Attributes weight')
    parser.add_argument('--weight_id', default=20, type=float, help='Identity Loss weight')
    parser.add_argument('--weight_rec', default=10, type=float, help='Reconstruction Loss weight')
    parser.add_argument('--weight_eyes', default=800., type=float, help='Eyes Loss weight')
 parser.add_argument('--eye_detector_loss', default=True, type=bool, help='If True eye loss with using AdaptiveWingLoss detector is applied to generator')
