### ISSUE TITLE
Предложение по исправлению ошибок

### ISSUE THREAD

**Issue by netrunner-exe** [sberbank-ai/sber-swap#24]
К сожалению не умею правильно делать пулл-реквесты, поэтому прошу разработчиков поправить или сделать пулл-реквест @AlexanderGroshev 

1. В `sberbank-ai/sber-swap/utils/inference/masks.py` строка 7 ` lmrks = np.array( lmrks.copy(), dtype=np.int )` нужно исправить на ` lmrks = np.array( lmrks.copy(), dtype=np.int32)` . Это уберёт предупреждения вроде `Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  lmrks = np.array( lmrks.copy(), dtype=np.int )` которых реально чересчур много и которые сильно забивают полезный вывод в консоль.
2. В `sber-swap/utils/inference/video_processing.py` строки 29 и 30 - в `os.system(f"ffmpeg -i` добавить` -v -8`, чтобы получилось `os.system(f"ffmpeg -v -8 -i {video_with_sound} -vn...` Это уберёт вывод работы FFmpeg и сделает вывод в консоль более чище и не будет забивать его лишней информацией.
3.  В `sber-swap/utils/inference/video_processing.py` строка 156 - исправить `cv2.VideoWriter_fourcc(*'MP4V')` на `cv2.VideoWriter_fourcc(*'mp4v')` - это решить проблему `OpenCV: FFMPEG: tag 0x5634504d/'MP4V'` и связанные с ней.

Остальное что нашёл в пулл-реквесте поправил @AlexanderGroshev. Спасибо!

**Comment by AlexanderGroshev** [comment]
Спасибо, @netrunner-exe!
Мы учли ваши предложения в последнем обновлении.

**Comment by netrunner-exe** [comment]
Спасибо!
