### ISSUE TITLE
 Vgg2 dataset cannot be downloaded

### ISSUE THREAD

**Issue by ShotaYamasaki** [sberbank-ai/sber-swap#90]
Hello
I can't download the Vgg2 dataset, so I'm at a loss as to how to fine tune it.
How should the parameters be adjusted if I use another dataset (such as Labeled Faces in the Wild)?

**Comment by mobassir94** [comment]
Download the dataset from here : https://drive.google.com/file/d/19pWvdEHS-CEG6tW3PdxdtZ5QEymVjImc/view

It's the exact same dataset that the authors of GHOST used.

**Comment by ShotaYamasaki** [comment]
thank you!
I'll try it right away!
